#!/usr/bin/env node

// Generate Atom feed from the repo issues.

// Reads a JSON formatted list of issues via STDIN. Such a list can be
// retrieved via /repos/:owner/:repo/issues?sort=created&direction=desc

const fs = require('fs')
const { Feed } = require('feed')
const { Converter } = require('showdown')
const converter = new Converter()

const author = {
  name: 'DJ Adams',
  email: 'qmacro@gmail.com',
  link: 'https://github.com/qmacro'
}

const issues = JSON.parse(fs.readFileSync(0, 'utf-8') || '[]')

if (issues.length === 0) process.exit(1)

const feed = new Feed({
  title: 'Thinking Aloud',
  description: 'A journal',
  id: 'https://github.com/qmacro/thinking-aloud',
  link: 'https://github.com/qmacro/thinking-aloud',
  generator: 'NPM module feed (https://www.npmjs.com/package/feed)',
  copyright: 'DJ Adams',
  author: author,
  feedLinks: {
    atom: 'https://github.com/qmacro/thinking-aloud',
  },
});

issues.forEach(issue => {
  feed.addItem({
    title: issue.title,
    id: issue.url,
    link: issue.html_url,
    content: converter.makeHtml(issue.body),
    author: author,
    date: new Date(issue.created_at),
    category: issue.labels.map(x => ( { name: x.name } ))
  })
})

console.log(feed.atom1())
