#!/usr/bin/env bash

# Runs in a GitHub Actions workflow job which has been triggered
# by the opening of an issue. Uses the GITHUB_EVENT_PATH env var
# to get to the file of JSON content representing the event info.

set -o errexit

declare title body url

title="$(jq -r .issue.title "$GITHUB_EVENT_PATH")"
body="$(jq -r .issue.body "$GITHUB_EVENT_PATH" | head -1 | cut -c -50)…"
url="$(jq -r .issue.html_url "$GITHUB_EVENT_PATH")"

echo "New 🧠 Thinking Aloud entry $title ($body) ☞ $url"
