name: Generate Atom Feed
on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      
    - uses: octokit/request-action@v2.0.26
      id: issues
      with:
        route: GET /repos/{owner}/{repo}/issues
        owner: qmacro
        repo: thinking-aloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - run: "echo latest release: ${{ steps.issues.outputs.data }}"
