name: Generate Atom Feed
on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
      
    - name: Setup Node.js environment
      if: ${{ false }}
      uses: actions/setup-node@v2.1.5
      
    - uses: octokit/request-action@v2.0.26
      id: issues
      with:
        route: GET /repos/{owner}/{repo}/issues
        owner: qmacro
        repo: thinking-aloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Install NPM modules
      if: ${{ false }}
      run: |
        npm install
        tree

    - uses: octokit/request-action@v2.0.26
      if: ${{ false }}
      id: get_latest_release
      with:
        route: GET /repos/{owner}/{repo}/releases/latest
        owner: octokit
        repo: request-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api /repos/qmacro/thinking-aloud/issues

