name: Generate Atom Feed
on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
      
    - name: Setup Node environment
      uses: actions/setup-node@v2.1.5
      
    - name: Install Node modules
      run: |
        npm install

    - name: Generate feed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api "/repos/${GITHUB_REPOSITORY}/issues?sort=created&direction=descending" \
          | ./feed \
          > feed.xml

    - name: Commit any updates
      run: |
        git config --global user.email "qmacro@gmail.com"
        git config --global user.name "DJ Adams"
        git diff --exit-code feed.xml || git add feed.xml && git commit -m 'update feed' && git push
