name: Generate Atom Feed
on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
      
    - name: Setup Node environment
      uses: actions/setup-node@v2.1.5
      
    - name: Install Node modules
      run: |
        npm install

    - name: Generate feed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api '/repos/qmacro-org/url-notes/issues?sort=created&direction=descending' \
          | ./feed

