name: Render most recent entries
on:
  issues:
      types: [opened, edited]
  workflow_dispatch:

jobs:
  generate:
    if: github.actor == github.repository_owner
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Setup Node environment
      uses: actions/setup-node@v2.1.5

    - name: Install Node modules
      run: |
        npm install

    - name: Render entries
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api "/repos/${GITHUB_REPOSITORY}/issues?sort=created&direction=descending" \
          | ./render \
          | tee recent.md

    - name: Commit any updates
      run: |
        git config --global user.email "qmacro@gmail.com"
        git config --global user.name "DJ Adams"
        git diff --exit-code recent.md || git add recent.md && git commit -m 'update render' && git push
